import {apiUrl} from '../config';
'use client';
import {useEffect,useState,useRef} from 'react';
import {Anchor,RefreshCw,MapPin,Clock,ShieldCheck,Radio,Route,Link as LinkIcon} from 'lucide-react';
import TrackMap from './map';
import {periodPoints} from './track-view';
import {coordinate,Position} from './positions';
type Reading={history:Position[];position:Position|null;sources:Position[];unavailable:boolean;storageUnavailable:boolean;checkedAt:string;schedule?:{port:{value:string};eta:{value:string};nextPort:{value:string}}|null};
const utc=(s:string)=>new Date(s).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'UTC'})+' UTC';
function age(s:string,now:number){const m=Math.max(0,Math.floor((now-Date.parse(s))/60000));return m<60?`${m} min`:m<1440?`${Math.floor(m/60)} h ${m%60} min`:`${Math.floor(m/1440)} dias e ${Math.floor(m%1440/60)} h`;}
export default function Page(){
 const [registration,setRegistration]=useState(''),[access,setAccess]=useState(false),[authBusy,setAuthBusy]=useState(false);const session=useRef('');
 const [data,setData]=useState<Reading|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[now,setNow]=useState(0),[copied,setCopied]=useState(false),[days,setDays]=useState(15);const lock=useRef(false);
 async function refresh(){if(!session.current||lock.current)return;lock.current=true;setBusy(true);const token=new URLSearchParams(location.hash.slice(1)).get('chave');
  try{if(!token)throw Error('Abra o link completo de acompanhamento que foi compartilhado com você.');const r=await fetch(apiUrl('/api/tracking'),{headers:{Authorization:`Bearer ${token}`,'X-Tracking-Session':session.current},cache:'no-store'});if(r.status===403){session.current='';setAccess(false);setData(null);throw Error('Sua sessão expirou. Informe a matrícula novamente.');}if(r.status===401){setData(null);throw Error('Este link é inválido ou foi revogado.');}if(!r.ok)throw Error('Não foi possível consultar agora. A última posição permanece na tela.');const next=await r.json() as Reading;setData(prev=>prev?.position&&next.position&&Date.parse(prev.position.dateTime)>Date.parse(next.position.dateTime)?{...next,position:prev.position}:next);setError('');}catch(e){setError(e instanceof Error?e.message:'Consulta indisponível.');}finally{setBusy(false);lock.current=false;setNow(Date.now());}}
 async function login(e:any){e.preventDefault();setAuthBusy(true);setError('');try{const key=new URLSearchParams(location.hash.slice(1)).get('chave');if(!key)throw Error('Abra o link autorizado completo.');const r=await fetch(apiUrl('/api/tracking/login'),{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({registration}),cache:'no-store'});const body=await r.json();if(!r.ok)throw Error(body.error||'Acesso indisponível.');session.current=body.token;setAccess(true);setRegistration('');await refresh();}catch(e){setError(e instanceof Error?e.message:'Acesso indisponível.');}finally{setAuthBusy(false);}}
 useEffect(()=>{setBusy(false);const timer=setInterval(()=>{setNow(Date.now());void refresh();},60000);const reset=()=>{session.current='';setAccess(false);setData(null);setError('');};window.addEventListener('hashchange',reset);return()=>{clearInterval(timer);window.removeEventListener('hashchange',reset);};},[]);
 if(!access)return <main><header><div className="brand"><Anchor size={25}/><h1>Acompanhamento do navio</h1></div></header><form className="access-card" onSubmit={login}><ShieldCheck size={28}/><h2>Acesso de tripulante</h2><p>Informe a matrícula cadastrada para abrir o acompanhamento.</p><label htmlFor="registration">Matrícula</label><input id="registration" autoComplete="off" value={registration} onChange={e=>setRegistration(e.target.value)} maxLength={80} required autoFocus/>{error&&<p role="alert" className="notice">{error}</p>}<button type="submit" disabled={authBusy}>{authBusy?'Verificando…':'Acessar'}</button></form></main>;
 const p=data?.position,old=p&&now-Date.parse(p.dateTime)>86400000;
 const visibleHistory=periodPoints(data?.history||[],days,now);
 const eta=data?.schedule?.eta?.value;const etaTime=eta?Date.parse(eta):NaN;
 const etaText=Number.isFinite(etaTime)&&etaTime<now?"Navio chegou ao porto":eta;

 return <main><header><div className="brand"><Anchor size={25}/><div><h1>Acompanhamento do navio</h1></div></div><span className="readonly"><ShieldCheck size={16}/>Acesso identificado · somente leitura</span></header><aside className="notice access-notice" aria-label="Aviso de acesso e compartilhamento"><strong>Acompanhamento informativo para tripulação e familiares.</strong> As posições são recebidas com atraso e não representam a localização do navio em tempo real. Compartilhe este link somente com <strong>autorização expressa do Comandante.</strong></aside>
 <section className="voyage-strip" aria-label="Programação do navio">{[["Próximo porto",data?.schedule?.port?.value],["ETA",etaText],["Possível próximo porto",data?.schedule?.nextPort?.value]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value||"Não informado"}</strong></div>)}</section>
 <section className="heading"><div><p className="eyebrow">POSIÇÃO E TRAJETO</p><h2>O navio no mapa</h2><p>VesselAPI, MarineTraffic e SPOT · último registro disponível</p></div><button onClick={refresh} disabled={busy}><RefreshCw size={17} className={busy?'spin':''}/>{busy?'Consultando…':'Atualizar'}</button></section>
 {error&&<p role="alert" className="notice">{error}</p>}
 {p?<><section className="position-strip" aria-label="Última posição registrada"><div><span><MapPin size={16}/>Coordenadas</span><strong>{coordinate(p.latitude,true)} <i>/</i> {coordinate(p.longitude,false)}</strong></div><div><span><Clock size={16}/>Idade do registro</span><strong className={old?'aged':''}>Há {age(p.dateTime,now)}</strong><small>{utc(p.dateTime)}</small></div><div><span><Radio size={16}/>Fonte selecionada</span><strong>{p.source}</strong><small>{old?'Registro com mais de 24 horas':'Último registro recebido'}</small></div></section><div className="map-toolbar"><div className="route-title"><Route size={18}/><b>Histórico de posições</b></div><div className="period-picker" role="group" aria-label="Período do histórico"><span>Visualizar últimos</span>{[15,30,45,90].map(value=><button key={value} aria-pressed={days===value} onClick={()=>setDays(value)}>{value} dias</button>)}</div></div><section className="mapwrap"><TrackMap position={p} history={visibleHistory} allHistory={data?.history||[]} days={days}/><div className="maplabel"><MapPin size={16}/>{p.source}</div></section><section className="history-summary"><div><h2>Trajeto registrado</h2><p><b>{visibleHistory.length}</b> registros nos últimos {days} dias{visibleHistory[0]?` · desde ${utc(visibleHistory[0].dateTime)}`:''}</p></div><details className="map-guide"><summary>Como interpretar o mapa</summary><p className="map-note">Pontos ligados por ordem de horário. Linhas tracejadas indicam intervalos maiores que 24 horas; as ligações não representam o trajeto exato. Toque em um ponto para ver horário e fonte.</p><p className="map-note">A proa indica a direção estimada entre os dois últimos pontos disponíveis, não o rumo medido. O histórico reúne registros recebidos, sem reconstruir posições ausentes.</p></details></section>{old&&<p className="notice">Este é o último registro disponível. Ele não confirma a localização do navio neste momento.</p>}{(data?.unavailable||data?.storageUnavailable)&&<p className="notice">{data.unavailable?'A fonte está temporariamente indisponível; exibindo a última posição guardada. ':''}{data.storageUnavailable?'O histórico guardado está temporariamente indisponível.':''}</p>}<details><summary>Horários das fontes</summary>{data?.sources.map(s=><p key={s.source}><b>{s.source}</b><span>{utc(s.dateTime)}</span></p>)}</details><footer><span>Consulta: {data&&utc(data.checkedAt)} · verificação automática a cada minuto</span><button onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setCopied(true);}catch{setError('Copie o link completo pela barra de endereço.');}}}><LinkIcon size={16}/>{copied?'Link copiado':'Copiar link'}</button></footer></>:!error&&<section className="empty">{busy?'Consultando a última posição…':'Nenhuma posição válida disponível.'}</section>}
 </main>;
}
